import {
  Sparkles,
  CircleCheckBig,
  TriangleAlert,
  BrainCircuit,
  Target,
  ArrowRight,
} from "lucide-react";

export default function Overview({ report,tab,setTab,title }) {
  const strengths = [
    "Strong Backend Development",
    "REST APIs & Microservices",
    "Node.js Fundamentals",
    "Database Knowledge",
  ];

  return (
    <div className="space-y-10">
      {/* Header */}

      <div>
        <div className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary-500/10 px-4 py-2 text-sm text-primary-300">
          <Sparkles size={16} />
          AI Generated Interview Report
        </div>

        <h1 className="mt-5 text-4xl font-black text-white">
          {title}
        </h1>

        <p className="mt-5 max-w-3xl text-lg leading-8 text-surface-400">
          Your resume has been compared against the uploaded job description.
          Here's a personalized interview preparation report generated by AI.
        </p>
      </div>

      {/* Quick Stats */}

      <div className="grid grid-cols-4 gap-5">
        <div className="rounded-3xl border border-surface-700 bg-surface-700/40 p-6">
          <p className="text-4xl font-black text-primary-300">
            {report.matchScore}%
          </p>

          <p className="mt-2 text-surface-400">Match Score</p>
        </div>

        <div className="rounded-3xl border border-surface-700 bg-surface-700/40 p-6">
          <p className="text-4xl font-black text-white">
            {report.technicalQuestions.length}
          </p>

          <p className="mt-2 text-surface-400">Technical Questions</p>
        </div>

        <div className="rounded-3xl border border-surface-700 bg-surface-700/40 p-6">
          <p className="text-4xl font-black text-white">
            {report.behavioralQuestions.length}
          </p>

          <p className="mt-2 text-surface-400">Behavioural Questions</p>
        </div>

        <div className="rounded-3xl border border-surface-700 bg-surface-700/40 p-6">
          <p className="text-4xl font-black text-warning">
            {report.skillGaps.length}
          </p>

          <p className="mt-2 text-surface-400">Skill Gaps</p>
        </div>
      </div>

      {/* Two Column */}

      <div className="grid grid-cols-[1.2fr_0.8fr] gap-8">
        {/* Strengths */}

        <div className="rounded-3xl border border-surface-700 bg-surface-700/40 p-8">
          <div className="mb-6 flex items-center gap-3">
            <CircleCheckBig className="text-accent-300" />

            <h2 className="text-2xl font-bold text-white">Your Strengths</h2>
          </div>

          <div className="space-y-5">
            {strengths.map((item) => (
              <div
                key={item}
                className="flex items-center gap-4 rounded-2xl bg-surface-800 p-5"
              >
                <CircleCheckBig size={18} className="text-accent-300" />

                <span className="text-surface-200">{item}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Weakness */}

        <div className="rounded-3xl border border-warning/20 bg-warning/5 p-8">
          <div className="mb-6 flex items-center gap-3">
            <TriangleAlert className="text-warning" />

            <h2 className="text-2xl font-bold text-white">Focus Areas</h2>
          </div>

          <div className="flex flex-wrap gap-3">
            {report.skillGaps.map((gap) => (
              <div
                key={gap.skill}
                className="rounded-full border border-warning/20 bg-warning/10 px-4 py-2 text-sm text-warning"
              >
                {gap.skill}
              </div>
            ))}
          </div>

          <div className="mt-10 rounded-2xl border border-primary-500/20 bg-primary-500/10 p-5">
            <div className="flex gap-3">
              <BrainCircuit className="text-primary-300" />

              <div>
                <h3 className="font-semibold text-white">AI Recommendation</h3>

                <p className="mt-2 leading-7 text-surface-300">
                  Complete the 7-Day Roadmap before attempting the mock
                  interview. Focus especially on Kubernetes and AWS.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CTA */}

      <div className="flex items-center justify-between rounded-3xl border border-primary-500/20 bg-primary-500/10 p-8">
        <div>
          <h2 className="text-2xl font-bold text-white">Ready to Start?</h2>

          <p className="mt-2 text-surface-300">
            Begin with the technical questions and work through the roadmap.
          </p>
        </div>

        <button
          onClick={() => {
            setTab("technical");
          }}
          className="flex items-center gap-3 rounded-2xl bg-primary-500 px-7 py-4 font-semibold text-white transition hover:bg-primary-400"
        >
          Start Preparation
          <ArrowRight size={20} />
        </button>
      </div>
    </div>
  );
}
